services:
  vite-app:
    build: .
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run preview -- --host
    networks:
      - caddy-net

  reverse-proxy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - caddy-net

networks:
  caddy-net:
